name: Block Progress Branch Merge

on:
  pull_request:
    branches: [main]

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Add warning comment
        uses: actions/github-script@v6
        with:
          script: |
            if ("${{ github.head_ref }}".startsWith("progress")) {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "⚠️ This PR is review-only. Do NOT merge via UI. Merge final changes from branch-review only."
              })
            }
      - name: Fail if branch starts with progress
        run: |
          if [[ "${GITHUB_HEAD_REF}" == progress* ]]; then
            echo "❌ Merging branches starting with 'progress' is not allowed via PR."
            exit 1
          else
            echo "✅ Branch allowed."
          fi

